### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by rahulljoshii** [openfin/openfin-cli#12]
I want to use [Sourcegraph](https://sourcegraph.com) for openfin-cli code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/openfin/openfin-cli. (It should only take 30 seconds.)

Thank you!

**Comment by rdepena** [comment]
@rahulljoshii this was done a while ago, closing. 

Thank you.
