### ISSUE TITLE
proxy/behind firewall support

### ISSUE THREAD

**Issue by DimitarChristoff** [openfin/openfin-cli#15]
typical setup, local env is behind a corporate firewall. shell, git, npm etc are all configured to use proxy but openfin-cli does not pick up settings and no way to specify it on the command line. 

```sh
> openfin -c src/app.json -l

using config C:\foo\html5-app\src\app.json
no rvm found at specified location, downloading from  https://developer.openfin.co/release/rvm/0.1.0.44
HTTPS download failed, trying http
launch failed [Error: Error: getaddrinfo ENOTFOUND developer.openfin.co developer.openfin.co:80]

  OpenFin Runtime cli tool

  OpenFin cli is capable of launching Application, and creating OpenFin config files.
  Options:
...
```

error cascaded from https://github.com/openfin/node-openfin-launcher/blob/master/lib/rvm-downloader.js (issue should be there) - `http.get()` supports options object which can have proxy settings (host, port).

suggested fix: either read `npm config get proxy` / `npm config get https-proxy` or env variables `HTTP_PROXY` and `HTTPS_PROXY` or allow passing proxy settings via cli.

**Comment by DimitarChristoff** [comment]
hey, can we have an update on this? I don't have much time to spend but something along the lines of:

https://gist.github.com/DimitarChristoff/6d53cb23299219d86d14

it does not work currently - 

```sh
no rvm found at specified location, downloading from  https://developer.openfin.co/release/rvm/0.1.0.44
HTTPS download failed, trying http { [Error: socket hang up] code: 'ECONNRESET' }
launch failed [Error: Error: socket hang up]
...
``` 
but it's getting further than before. it's compounded by the fact that the proxy has its own SSL certificate as 'man in the middle' so I assume it would work for normal proxied environments - `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` does not appear to work. 

may be an idea to use npm module. also relevant - http://blog.vanamco.com/proxy-requests-in-node-js/ etc.

**Comment by wenjunche** [comment]
Hello 

Have you tried:

npm --https-proxy=http://company.proxy.com

Or:

npm config set strict-ssl false

**Comment by DimitarChristoff** [comment]
yes, ignored entirely.

**Comment by wenjunche** [comment]
We just updated node-openfin-launcher module to address the issue.  Please run "npm udpate" and try.

I tested the change by setting

HTTPS_PROXY=http://username:password@proxyHost:port

**Comment by DimitarChristoff** [comment]
can confirm this now works. thanks - closing.

**Comment by codystott** [comment]
@stephenrooban I got it working by setting `HTTPS_PROXY` as an environment variable using `export HTTPS_PROXY=http://username:password@proxyHost:port`

**Comment by MarioVilas** [comment]
Does not seem to be working for me:

```
HTTPS_PROXY=http://localhost:8080 openfin -l -u http://example.com
```

I am getting errors in the proxy, apparently openfin is trying to fetch relative URIs instead of full URLs?

I get different errors if I set it like this:

```
HTTPS_PROXY=localhost:8080 openfin -l -u http://example.com
```

Changing or adding HTTP_PROXY instead of HTTPS_PROXY does not help either.
