### ISSUE TITLE
Can the cli be installed without the -g option?

### ISSUE THREAD

**Issue by aesalazar** [openfin/openfin-cli#23]
Is it possible to do a local install of the npm package?  

It is not a big deal to do a global but it would be nice to do have the local option to minimize the foot print and it can be included in the projects package.json.  So when a new developer does the npm install after cloning the repo it is taken care of.

Thanks
Ernie

**Comment by rdepena** [comment]
Hey @aesalazar , 

The cli tool can be installed locally and you can launch from the node_modules folder, for example:

`npm install openfin-cli`

`node node_modules\.bin\openfin --help`

**Comment by aesalazar** [comment]
Thanks @rdepena.  That works great using `node_modules\.bin\openfin --help`! (without that extra `node`).

Appreciate the help.
Ernie

**Comment by rdepena** [comment]
@aesalazar awesome. np.
