### ISSUE TITLE
multiple runtime arguments improperly parsed

### ISSUE THREAD

**Issue by rmethlie** [openfin/openfin-cli#25]
I am attempting to launch OpenFin using openfin-cli and an app.json config.

When given this "runtime" config object:

```JavaScript
"runtime": {
        "arguments": "--ignore-certificate-errors --remote-debugging-port=9222",
        "version": "stable"
    },
```
the terminal displays the following for the runtime arguments:

```bash
[INFO:atom_api_app.cc(862)] 03/14 15:11:51.595 - {"_":["/Users/Russ/OpenFin/Runtime/6.49.17.14/OpenFin.app/Contents/MacOS/OpenFin"],"startup-url":"\"app.json\" ","ignore-certificate-errors --remote-debugging-port":9222}
```

Note the failure to properly parse multiple arguments.  Clearly it should be:

```
{..., "ignore-certificate-errors": true, "remote-debugging-port": 9222}
```

The effect is that neither argument is respected.

**Comment by rmethlie** [comment]
Any chance of getting this one looked at?

**Comment by rdepena** [comment]
@rmethlie yes, I will take a look sometime this week. 

Thanks for reporting this issue.

**Comment by rdepena** [comment]
fixed in https://github.com/openfin/node-openfin-launcher/pull/30

**Comment by rmethlie** [comment]
thanks much

**Comment by rdepena** [comment]
Confirmed fix in [openfin-launcher](https://www.npmjs.com/package/openfin-launcher) version 1.3.12
