### ISSUE TITLE
Linux default runtime is compiled for ARM, not x64

### ISSUE THREAD

**Issue by merildev** [openfin/openfin-cli#27]
Hi,

When I use:

```
openfin -l -c path/to/my/config.json
```

To run my app with the following config.json:

``` javascript
"runtime": {
    "arguments": "",
    "version": "beta-next"
}
```

The runtime client that is downloaded is:
https://developer.openfin.co/release/runtime/linux/x64/7.53.20.20

Then I get the error: 

```
openfin: cannot execute binary file
126
```

After further investigations I noticed that the binary:

```
~/OpenFin/Runtime/7.53.20.20/openfin
```

is compiled for ARM, not x86-64.

Edit: the runtime 6.49.20.22 (stable-v6) is fine, compiled for x86-64.

**Comment by rdepena** [comment]
This is a good find, thank you. we are looking into this.

**Comment by merildev** [comment]
Do you have any news on this?
