### ISSUE TITLE
Not able to start the app on Windows

### ISSUE THREAD

**Issue by braxnu** [openfin/openfin-cli#34]
Hi
I'm trying to play with openfin-cli and following this manual https://openfin.co/documentation/getting-started/
The installation step finishes successfully, but when I try to launch it, I get this error:
```
Error: spawn UNKNOWN                                                                                                       
    at ChildProcess.spawn (internal/child_process.js:357:11)                                                               
    at spawn (child_process.js:528:9)                                                                                      
    at C:\Users\braxnu\AppData\Roaming\npm\node_modules\openfin-cli\node_modules\openfin-launcher\src\win-launcher.js:23:27
    at FSReqWrap.oncomplete (fs.js:183:5)
```
I get the same error for various URLs and tried it on Win7-64 and Win10.
Please, could you advice on how to fix this?

**Comment by TonyBarkell** [comment]
Hi,

We have not been able to replicate this behaviour.  You please contact support@openfin.co and include:

* The full output from the console,
* Any logs located in %localappdata%\openfin\logs
* The debug.log file located in %localappdata%\openfin\9.61.32.38

**Comment by TonyBarkell** [comment]
Hi,

Further to the above, we have seen this error when launching from the CLI with a slow network connection pulling down from the CDN. Can you please try:

1) Head to %LOCALAPPDATA%\OpenFin
2) Delete everything in this directory
3) Download the latest RVM from this link https://developer.openfin.co/release/rvm/4.4.0.13
4) Add .zip to the end of that file name - so 4.4.0.13would become 4.4.0.13.zip
5) Unzip - you should see OpenFinRVM.exe
6) Drag the OpenFinRVM.exe to the %LOCALAPPDATA%\OpenFin directory

**Comment by braxnu** [comment]
Hi @TonyBarkell Thanks for a super quick response. 

I didn't have any folders or files in my %LOCALAPPDATA%\OpenFin apart from the OpenFinRVM.exe itself. It looked like crashing straight after start. The only error I got was the one pasted in the report.

Luckilly the new version works perfectly with Win7. I'll update when I test on Win10.

Many thanks

If I can suggest, it would be much more user-friendly if you updated the binary installed with npm. Best!

**Comment by braxnu** [comment]
I guess the problem is solved now. Closing the issue.
